---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-deployment-config
  namespace: ktask
data:
  SONG_SVC_URL: "song-svc"
  SONG_SVC_PORT: "8080"
  RESOURCE_SVC_PORT: "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-svc-db-init-config
  namespace: ktask
data:
  init-resource-svc-db.sql: |
    CREATE DATABASE resource_svc_db;
    \c resource_svc_db;
    CREATE TABLE resource
    (
    id         SERIAL PRIMARY KEY,
    audio_data BYTEA NOT NULL
    );

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: song-svc-db-init-config
  namespace: ktask
data:
  init-song-svc-db.sql: |
    CREATE DATABASE song_svc_db;
    \c song_svc_db;
    CREATE TABLE song
    (
    id           SERIAL PRIMARY KEY,
    resource_id  INT,
    artist       VARCHAR(255),
    name         VARCHAR(255),
    album        VARCHAR(255),
    release_year VARCHAR(4),
    duration     VARCHAR(10),
    genre        VARCHAR(255)
    );
