---
apiVersion: v1
kind: Service
metadata:
  name: resource-svc-db
  namespace: ktask
spec:
  type: ClusterIP
  selector:
    app: resource-svc-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: song-svc-db
  namespace: ktask
spec:
  type: ClusterIP
  selector:
    app: song-svc-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
