---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.resourceSvc.name }}-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.resourceSvc.name }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.resourceSvc.name }}-db
  template:
    metadata:
      labels:
        app: {{ .Values.resourceSvc.name }}-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine3.18
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.resourceSvc.name }}-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{ .Values.resourceSvc.name }}-db-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb-{{ .Values.resourceSvc.name }}-db
              mountPath: /docker-entrypoint-initdb.d/init-{{ .Values.resourceSvc.name }}-db.sql
              subPath: init-{{ .Values.resourceSvc.name }}-db.sql
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 25
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 10
      volumes:
        - name: initdb-{{ .Values.resourceSvc.name }}-db
          configMap:
            name: {{ .Values.resourceSvc.name }}-db-init-config
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.resourceSvc.name }}-db-storage
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
