---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.songSvc.name }}-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.songSvc.name }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
