---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.songSvc.name }}-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: "MTExMQ=="
  DB_USERNAME: "cG9zdGdyZXM="
  DB_PASSWORD: "MTExMQ=="
stringData:
  DB_HOST: "{{ .Values.songSvc.name }}-db"
