---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.songSvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.songSvc.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
